# 服务端口
server:
  port: 11000

spring:
  # mysql数据库连接
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/louismall_pms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # thymeleaf
  thymeleaf:
    cache: false

  # redis
  redis:
    host: 192.168.56.10
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      # 如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      # key-prefix: CACHE_
      use-key-prefix: true
      # 是否缓存空值null，防止缓存穿透
      cache-null-values: true
  session:
    store-type: redis

# mybatis-plus相关配置
mybatis-plus:
  # 配置mapper xml文件的路径
  mapper-locations: classpath:/mapper/**/*.xml
  # mybatis自增
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.louisblogs.louismall: debug

#配置自定义的线程池
louismall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
