# 服务端口
server:
  port: 12000

spring:
  # 服务名
  application:
    name: louismall-ware

  # mysql数据库连接
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/louismall_wms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#      alibaba:
#        seata:
#          tx-service-group: louismall-ware-fescar-service-group
    #配置sentinel
    sentinel:
      transport:
        dashboard: localhost:8333
        #控制台的port
        port: 8719

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # RabbitMQ配置
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    # 开启发送端确认
    publisher-confirms: true
    # 开启发送端消息抵达队列的确认
    publisher-returns: true
    # 只要抵达队列，以异步发送优先回调我们这个returnconfirm
    template:
      mandatory: true
    # 手动ack消息
    listener:
      simple:
        acknowledge-mode: manual

  #配置Zipkin链路追踪可视化展示
  zipkin:
    base-url: http://192.168.56.10:9411/
    #关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      #设置采用http的方式
      type: web
  sleuth:
    sampler:
      #配置sleuth采样器 100%
      probability: 1

# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # mybatis自增
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.louisblogs: debug

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#management.endpoints.web.exposure.include=*
#配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all