# 服务端口
server:
  port: 20000

spring:
  # 服务名
  application:
    name: louismall-auth-server

  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #配置sentinel
    sentinel:
      transport:
        dashboard: localhost:8333
        #控制台的port
        port: 8719

  thymeleaf:
    cache: false

  # redis
  redis:
    host: 192.168.56.10
    port: 6379

  session:
    store-type: redis

  # 过期时间
  servlet:
    session:
      timeout: 30m

  #配置Zipkin链路追踪可视化展示
  zipkin:
    base-url: http://192.168.56.10:9411/
    #关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      #设置采用http的方式
      type: web
  sleuth:
    sampler:
      #配置sleuth采样器 100%
      probability: 1

#management.endpoints.web.exposure.include=*
#配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all
