# \u670D\u52A1\u7AEF\u53E3
server:
  port: 20000

spring:
  # \u670D\u52A1\u540D
  application:
    name: louismall-auth-server

  # nacos\u670D\u52A1\u5730\u5740
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false

  # redis
  redis:
    host: 192.168.56.10
    port: 6379

  session:
    store-type: redis

  # 过期时间
  servlet:
    session:
      timeout: 30m
