# \u670D\u52A1\u7AEF\u53E3
server:
  port: 13000

spring:
  application:
    name: louismall-search

  # \u914D\u7F6Enacos\u6CE8\u518C\u4E2D\u5FC3
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
