# 服务端口
server:
  port: 13000

spring:
  application:
    name: louismall-search

  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # thymeleaf
  thymeleaf:
    cache: false
