# 服务端口
server:
  port: 40000

spring:
  application:
    name: louismall-cart

  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #配置sentinel
    sentinel:
      transport:
        dashboard: localhost:8333
        #控制台的port
        port: 8719

  redis:
    host: 192.168.56.10

  #配置Zipkin链路追踪可视化展示
  zipkin:
    base-url: http://192.168.56.10:9411/
    #关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      #设置采用http的方式
      type: web
  sleuth:
    sampler:
      #配置sleuth采样器 100%
      probability: 1

#配置自定义的线程池
louismall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

#management.endpoints.web.exposure.include=*
#配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all


