# \u670D\u52A1\u7AEF\u53E3
server:
  port: 40000

spring:
  # \u670D\u52A1\u540D
  application:
    name: louismall-cart

  # \u914D\u7F6Enacos\u6CE8\u518C\u4E2D\u5FC3
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 192.168.56.10

#\u914D\u7F6E\u81EA\u5B9A\u4E49\u7684\u7EBF\u7A0B\u6C60
louismall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

