# 服务端口
server:
  port: 40000

spring:
  application:
    name: louismall-cart

  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 192.168.56.10

#配置自定义的线程池
louismall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

