# 服务端口
server:
  port: 30000

spring:
  # mysql数据库连接
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/louismall_pms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alicloud:
      access-key: access-key
      secret-key: secret-key
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: louismall

      sms:
        host: https://zwp.market.alicloudapi.com
        path: /sms/sendv2
        appcode: 0c3f3757f5b74beeb79a59975070b36d

# mybatis-plus相关配置
mybatis-plus:
  # 配置mapper xml文件的路径
  mapper-locations: classpath:/mapper/**/*.xml
  # mybatis自增
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.louisblogs.louismall: debug
