# 服务端口
server:
  port: 25000

spring:
  application:
    name: louismall-seckill

  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #配置sentinel
    sentinel:
      transport:
        dashboard: localhost:8333
        #控制台的port
        port: 8719

#  task:
#    scheduling:
#      pool:
#        size: 5

  #spring给我们配的线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

  # redis
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis

  # RabbitMQ配置
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    # 开启发送端确认
    publisher-confirms: true
    # 开启发送端消息抵达队列的确认
    publisher-returns: true
    # 只要抵达队列，以异步发送优先回调我们这个returnconfirm
    template:
      mandatory: true
    # 手动ack消息
    listener:
      simple:
        acknowledge-mode: manual

  thymeleaf:
    cache: false

  #配置Zipkin链路追踪可视化展示
  zipkin:
    base-url: http://192.168.56.10:9411/
    #关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      #设置采用http的方式
      type: web
  sleuth:
    sampler:
      #配置sleuth采样器 100%
      probability: 1

#management.endpoints.web.exposure.include=*
#配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all

# 开启debug日志
logging:
  level:
    com.louisblogs.louismall: debug
    org:
      springframework:
        cloud:
          openfeign: debug
          sleuth: debug



